### ISSUE TITLE
Blink to Blink game transmission

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-SDK#40]
This is perhaps the most important part of the BlinkOS. The architecture is as follows:

| ATMega168pb [16KB] |
|-----------------------|

_zoom in_

| BlinkOS [6KB]| Game(static) [5KB] |
|---------|--------------|
| ~~Loading Dock~~ | __Game(active) [5KB]__|

__BlinkOS__ - responsible for sleep and wake functions, power management, all basic display functionality, communications and ability to transmit games and validate received games.

__Game(static)__ - holds the game this Blink is programmed to know. This game is the game that the Blink will transmit to other Blinks when programming mode is invoked

__Game(active)__ - holds the game this Blink is programmed to play. This could be a game received from another Blink, or could simply be a pointer to the game this Blink already knows.

~~__Loading Dock__ - holds a game during transmission until the game is validated, then replaces the Game(active)... only after validation, otherwise the loading dock is cleared and ready to receive a new game again.~~

**Comment by bigjosh** [comment]
I don't think you need/want the `loading dock` section. I would just receive new games directly into the `active` section. 

CON: If a game transfer aborts fails, then you would need to do another successful game transfer but I think this is OK behavior. 

PRO: You get significantly more memory for games since now the maximum size for a game is 1/2 the available flash rather than 1/3.

**Comment by kenj1** [comment]
During game development (debug mode), the game size may exceed 4kB (debug statements) and slimmed down to <4kB before final release & transmission.   It's not described how you're enforcing these limits, so...  I think it'd be better if the game area sizes (static and active) are only checked/enforced when the user tries to use game transmission.  If instead the sizes are hardwired and enforced all the time (even during game dev) than users are actually limited to a much smaller game footprint.  

Also, Joshs comment makes sense to me and gives more breathing room for game dev.

**Comment by jbobrow** [comment]
I'm open to this idea of getting rid of the loading dock. One of the first principles of my design is to fail gracefully. Being in a state without a game to play feels like it could be frustrating for players. It is a new behavior that has to be obvious to the user. I can think of a number of ways to animate this, and intuition will only take me so far, so testing out how this feels would ideally inform this decision.

Nice suggestion @kenj1 for warning on game transmission, having a clear way of knowing that your game is capable of being transmitted will be important for developers, as I can tell, we already have ambitious devs :)

@bigjosh I'll share a fail state animation that simply loops until the Blink is reprogrammed and we can give that a shot. Would the loading dock be a major change to the architecture? I do agree that more game space, could be good thing (given that our transmission times are within reason)

**Comment by bigjosh** [comment]
> Being in a state without a game to play feels like it could be frustrating for players. 

In the case of a failed transmission, the blink would have its "static" game. I think if you walk though the cases where you would have a failed or aborted transmission, this makes about the same sense as falling back to whatever the most recently successfully received game happened to be.  

> Would the loading dock be a major change to the architecture?

No change, just about saving space.

**Comment by jbobrow** [comment]
> In the case of a failed transmission, the blink would have its "static" game. I think if you walk though the cases where you would have a failed or aborted transmission, this makes about the same sense as falling back to whatever the most recently successfully received game happened to be.

I think this makes sense. I imagine a group of n Blinks are together and receiving a program, the likelihood of all Blinks failing to receive the entire game is low, and the likelihood that some of the Blinks fail to receive the entire game is higher. Either way, having the previous game you were playing on the Blinks that didn't receive the new game is probably useless since you want it on all of the Blinks... That said, I think it still makes sense to signal that the transmission didn't succeed and make the user put that Blink into the correct state. By simply returning to its known game, it could be confusing to have a field of n-2 Blinks with the correct game and 2 Blinks playing their own games... might be nicer to see the two Blinks in an SOS pattern (or similar animation).

**Comment by kenj1** [comment]
Something else to think about.  I've found it difficult to know what game is actually on a Blink, and in the case you're proposing of 2 possible game areas (static and active) it makes it even a little more complicated.  Being able to tell visually by game start animation isn't great as some games may use similar animation, and the user has to remember which animation is associated with which game.  

Maybe knowing that all connected Blinks have the same game is useful (no need to reprogram).  This may be easily achievable if you put one in program mode and have it query to see if the other Blinks have the same game.  E.g. the connected Blink shows green if their the same as the programming Blink, and red if they're not.  That way you can easily tell which Blinks you need to reprogram.

Thoughts??

**Comment by bigjosh** [comment]
Right now blinks always accept the a game download unconditionally, but one optimization I've considered is to have the receiving blink check the checksum of the incoming game against the checksum of the already loaded active game. If the checksums match then thew blink assumes that it already has the downloaded game and immediately starts seeding. The downside of this strategy is that it break badly if two games ever happened to end up with the same checksum (aprox 1 in 65536 chance for any 2 games). We could make sure that all officially published games have unique checksums, but they could always collide with user developed games. 

One thing to take into account is that having a blink in of a chain of blinks skip doing a redundant download because it already has the game loaded really only saves less than 1 sec total if there are any blinks in the chain that do need the download.

**Comment by jbobrow** [comment]
Handling of the error situations is an area to clean up, but overall this is working quite well. Closing the issue in this repo
