### ISSUE TITLE
Game restart (enhancement request)

### ISSUE THREAD

**Issue by kenj1** [Move38/Blinks-SDK#45]
A very necessary feature when playing a game on Blinks is to reset and place them all back at game start.  It makes sense to make this part of the new menu being proposed.  The easiest way I can see to accomplish this is to (1) sleep followed by (2) wakeup the Blink (and connected Blinks) in order for them to rerun Setup().  This assumes the programmer resets their game parameters to game start whenever Setup() is run.

**Comment by bigjosh** [comment]
I think it is possible for the game to implement this behavior if desired by checking `hasWoke()` in `loop()` and calling `setup()` if it did just wake up?

**Comment by jbobrow** [comment]
We are going to publish to the forum some standards on button clicks. We have often used Double-Click to both start and reset gameplay.
