### ISSUE TITLE
Mortals compilation error

### ISSUE THREAD

**Issue by mgrider** [Move38/Blinks-SDK#55]
Maybe this is already fixed, because I'm not 100% sure I know which version of the API I have installed. (So feel free to close as FIXED if so! Tangentially, it might be nice to have a guide for installing the API from git rather than from .zip file, so it's easy to update and / or see which version you have installed.)

Essentially, after opening `File->Examples->03. Getting Playful->A-MortalsGame`, hitting the Verify button in Arduino causes the following error:
```
/Users/[redacted]/Documents/Arduino/hardware/BlinkOS/avr/libraries/Examples03/examples/A-MortalsGame/A-MortalsGame.ino: In function 'void setup()':
A-MortalsGame:54:19: error: 'blinkStateBegin' was not declared in this scope
   blinkStateBegin();
                   ^
exit status 1
'blinkStateBegin' was not declared in this scope
```

**Comment by jbobrow** [comment]
Master updated. Thanks for this find. A little late to the issue :)
