### ISSUE TITLE
Special function for game that completed teaching of game

### ISSUE THREAD

**Issue by jbobrow** [Move38/Blinks-SDK#67]
Forward thinking feature for games that might want to do something starting with the "Master" Blink, the one that taught all others how to play. A simple example is having a message only come from the teacher at the end of load to put all pieces into setup... Not immediately necessary, but like the thought of having access to this.

**Comment by bigjosh** [comment]
Hmmm..,. this was in the BIOS code but not sure if it survived the space purge. Will check!

**Comment by jbobrow** [comment]
Note, this is for the future. Not V1 approved

**Comment by jbobrow** [comment]
Added just before gold master :)
