### ISSUE TITLE
Feature Request: lighten()

### ISSUE THREAD

**Issue by ReluctantPirate** [Move38/Blinks-SDK#81]
Just had an idea for a new color function: lighten(). This would function similarly to the dim() function, except in the case of lighten it would transition from the color itself to pure white. For example:

lighten(RED, 0) would appear as just RED
lighten(RED, 255) would appear as pure white
lighten(RED, 127) would appear as desaturated red (essentially R-255 G-127 B-127)

This could help developers make white flashes (a common animation trick) with RGB-defined colors.

**Comment by bigjosh** [comment]
Does seem only fair to be symmetrical with `dim()`. Maybe the two functions should be renamed `toWhite(c,b)` and `toBlack(c,b)`. Heck maybe be general with `toColor(from,to,step)`?

Note that these can all be added to any program now by just including them at the top or in an include file. They can also be added to the API with the only risk being breaking existing code that may have these names already used.

**Comment by ReluctantPirate** [comment]
I think dim() is already really clear, and lighten() seems like a nice parallel.

That being said, the generic color changing would be awesome as a function. Maybe something like colorShift() or colorChange() or colorSlide().

**Comment by bigjosh** [comment]
Ok, someone check my math here!...

```
Color lighten( Color color, byte brightness) {
    return MAKECOLOR_5BIT_RGB(
        (GET_5BIT_R(color) + (((MAX_BRIGHTNESS- GET_5BIT_R(color))*brightness)/MAX_BRIGHTNESS )),
        (GET_5BIT_G(color) + (((MAX_BRIGHTNESS- GET_5BIT_R(color))*brightness)/MAX_BRIGHTNESS )),
        (GET_5BIT_B(color) + (((MAX_BRIGHTNESS- GET_5BIT_R(color))*brightness)/MAX_BRIGHTNESS ))
    );
}

```

**Comment by bigjosh** [comment]
> That being said, the generic color changing would be awesome as a function

Note that there are multiple ways to interpolate between colors...

https://www.alanzucconi.com/2016/01/06/colour-interpolation/2/

I think you can implement any of them using the current `makeColorRGB()` and `makeColorHSV()` functions?

**Comment by bigjosh** [comment]
Ok, new `lighten()` included in current open PR. 

Here is `LightenTest.ino`...

```
void setup() {
  // put your setup code here, to run once:

}


Color baseColors[] = { RED, GREEN , BLUE, ORANGE , OFF , YELLOW };

byte colorIndex=0;
byte brightness=0;

Timer nextStep;

const unsigned STEP_TIME_MS  = 1;

void loop() {

  if (nextStep.isExpired()) {

    if (brightness < MAX_BRIGHTNESS) {

      brightness++;

    } else {

      brightness = 0;

      colorIndex++;

      if (colorIndex == COUNT_OF( baseColors ) ) {
        colorIndex = 0;
      }

    }

    nextStep.set( STEP_TIME_MS );

  }

  setColor( lighten( baseColors[colorIndex] , brightness ) );
  

}
```
